### ISSUE TITLE
yeoman

### ISSUE THREAD

**Issue by nemesiscodex** [nemesiscodex/yvy-ui#1]
Proyecto inicial yeoman angularJS

**Comment by rparrapy** [comment]
- Subí el proyecto generado con: https://github.com/yeoman/generator-angular
- Modifiqué el README con las instrucciones de instalación.
- Al instalar dependencias en el cliente, usar siempre

``` bash
bower install --save [dependencia]
```

Para mantener las dependencias sincronizadas con todo el equipo.
- Agregué [lodash](https://lodash.com/) como librería utilitaria. Es buena idea por varias razones: menos verbosity, compatibilidad cross-browser, etc.
